# Use an official Node runtime as a base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/client

# Copy package.json and package-lock.json to the container
COPY client/package*.json ./

# Install app dependencies
RUN npm install

# Copy the client application code to the container
COPY client/ .

# Build the client app
RUN npm run build

# Expose the port that the app will run on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "start"]
