# Use an official Node runtime as a base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/server

# Copy package.json and package-lock.json to the container
COPY server/package*.json ./

# Install app dependencies
RUN npm install

# Copy the server application code to the container
COPY server/ .

# Expose the port that the app will run on
EXPOSE 5000

# Define the command to run your app
CMD ["npm", "start"]
